In [1]:
import numpy as np
import matplotlib as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
import tensorflow as tf

In [3]:
tf.__version__




'2.2.0'

In [4]:
a = tf.constant(2,dtype=np.int64)

In [5]:
a

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [7]:
b = a+1

In [10]:
b.numpy()


3

In [12]:
a_mat = tf.constant([[1,2],[3,4]])
b_mat = tf.constant([[1,2],[3,4]])

In [13]:
tf.matmul(a_mat,b_mat)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [14]:
a = tf.Variable(3,dtype = np.int64)

In [15]:
a

<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=3>

In [16]:
a.numpy()

3

In [17]:
a.assign(20202)

<tf.Variable 'UnreadVariable' shape=() dtype=int64, numpy=20202>

In [18]:
a

<tf.Variable 'Variable:0' shape=() dtype=int64, numpy=20202>

In [37]:
k = tf.Variable(54)

In [38]:
k

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=54>

In [39]:
j = k

In [40]:
j is k

True

In [41]:
k.assign(j)
j is k

True

In [42]:
k = k+1

In [43]:
j is k

False

In [44]:
v = tf.Variable([[3.,3.2], [1.2,2.2]], dtype=tf.float32, name='my_variable')

print('name  : ', v.name)
print('type  : ', v.dtype)
print('shape : ', v.shape)
print('device: ', v.device)

name  :  my_variable:0
type  :  <dtype: 'float32'>
shape :  (2, 2)
device:  /job:localhost/replica:0/task:0/device:CPU:0


In [45]:
mat  = tf.Variable(np.random.randint(0,100,(10,10)))

In [46]:
mat

<tf.Variable 'Variable:0' shape=(10, 10) dtype=int64, numpy=
array([[48, 41,  6,  2, 19, 74, 47, 65, 52,  2],
       [47, 23, 85, 98, 55, 69, 35, 13, 67, 28],
       [ 3, 61, 16, 25, 97, 72, 33, 32, 13, 13],
       [82, 63, 25, 14, 71, 26, 79, 70, 91,  9],
       [33, 24, 64, 40, 17, 50, 49, 68, 24, 32],
       [47, 52, 84, 81, 22, 83, 19, 94, 79, 42],
       [90, 76, 46, 19, 84, 21, 42, 96, 81, 76],
       [14, 87, 64, 55, 35,  2, 22, 76, 24, 99],
       [48, 98, 59, 12, 23, 84, 17, 80,  3, 97],
       [48, 24, 57, 83, 65, 41, 56, 34, 64, 65]])>

In [48]:
tf.reduce_sum(mat,axis=0)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([460, 549, 506, 429, 488, 522, 399, 628, 498, 463])>

In [49]:
tf.reduce_mean(mat)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [50]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int64, numpy=20205>

In [51]:

v = a+b
u = v+2
w = v*u
z = w*3
z

<tf.Tensor: shape=(), dtype=int64, numpy=1224847305>

In [54]:
@tf.function
def func(a,b):
     z = tf.multiply(a, b, name='z')
     y1 = tf.constant(3, name='3')
     y2 = tf.constant(4)
     w1 = tf.add(z, y1, name='w1')
     w2 = tf.add(z, y2, name='w2')
     return(w1+w2)




In [55]:
p = tf.Variable(10)
q = tf.Variable(20)



In [56]:
p,q

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>)

In [57]:
func(p,q)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [61]:
with tf.GradientTape() as tape:
    w = tf.Variable(10,dtype = tf.float32)
    out  = w * w + 10 * w
print(out)
grad = tape.gradient(out,w)
print(grad)


tf.Tensor(200.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)
